# name = "leonardorick"
# main = "./.output/server/index.mjs"
# workers_dev = true
# compatibility_date = "2023-05-18"
# # account_id = "<the account_id you obtained (optional)>"
# # route = "<mainly useful when you want to setup custom domains (optional too)>"

# [site]
# bucket = ".output/public"